#!/usr/bin/env python
# coding: utf-8

# In[4]:
import time
import threading
import tensorflow as tf
from filelock import FileLock as lck
import shutil
#default our libary to generate errpr data.
from Lib.image import ImageDataGenerator, array_to_img, img_to_array, load_img
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Activation, Dropout, Flatten, Dense
from keras.models import load_model
from keras import backend as K
import numpy as np 
import cv2
from matplotlib import pyplot as plt
import imutils
import glob
import os
import argparse
#Data train with 4000 pictures: 2000 train - 3000 validation
#Data test with 800 pictures: 200 train - 600 validation

K.clear_session()
lck = threading.Lock()

parser = argparse.ArgumentParser(description="Enter your URL template image: ")
parser.add_argument('--mainUrl', dest='main_url') # Directory của layout.png
parser.add_argument('--templateFolder', dest='template_folder') # folder chứa tất cả hình mẫu.
parser.add_argument('--models', dest='models') # folder chứa các model khi train xong.
parser.add_argument('--txt', dest='filename') # 
args = parser.parse_args()
#Lấy các biến tham số từ args để tiện cho việc gọi.
main_Image = args.main_url
main_img = cv2.imread(main_Image,0) 
main_width, main_height = main_img.shape[::-1] # lấy chiều dài chiều rộng của Layout.
fileLocation = args.filename
with open(fileLocation, 'w') as f:
        f.write('1\n') 
        f.close()
img_path = args.template_folder
#im = cv2.imread(img_path,0) #get height and width of template image.
#template_width, template_height = im.shape[::-1]
model_dir = args.models

#Generate normal true data.
def GenerateDataTrain(img_path):
    datagen = ImageDataGenerator(
        featurewise_center=True,
        rescale=1./255,
        fill_mode = 'nearest')

    img = load_img(img_path)
    x = img_to_array(img)
    x = x.reshape((1,) + x.shape)
    i = 0
    for batch in datagen.flow(x, batch_size = 1,
                            save_to_dir ='DataGeneration/train/Data', save_prefix='Data', save_format='jpeg'):
        i+= 1
        if i == 2001:
            break
    
    j = 0
    path, dirs, files = next(os.walk("DataGeneration/train/Data"))
    file_count = len(files)
    if(file_count != 2000):
        for batch in datagen.flow(x, batch_size = 1,
                               save_to_dir ='DataGeneration/train/Data', save_prefix='Data_A', save_format='jpeg'):
            j+= 1
            if(j == 2000 - file_count):
                break

#Generate normal true data.
def GenerateDataTrainMist(img_path):
    datagen = ImageDataGenerator(
        width_shift_range=0.3,
        rescale=1./255,
        featurewise_center=True,
        height_shift_range=0.3,
        fill_mode= 'constant', cval = 255)

    img = load_img(img_path)
    x = img_to_array(img)
    x = x.reshape((1,) + x.shape)
    i = 0
    for batch in datagen.flow(x, batch_size = 1,
                            save_to_dir ='DataGeneration/train/Mist', save_prefix='Mist', save_format='jpeg'):
        i+= 1
        if i == 1001:
            break

    j = 0
    path, dirs, files = next(os.walk("DataGeneration/train/Mist"))
    file_count = len(files)
    if(file_count != 1000):
        for batch in datagen.flow(x, batch_size = 1,
                               save_to_dir ='DataGeneration/train/Mist', save_prefix='Mist_A', save_format='jpeg'):
            j+= 1
            if(j == 1000 - file_count):
                break
            
#Generate mist data with X wrong.
def GenerateDataMist_X(img_path):
    datagen = ImageDataGenerator(
        width_shift_range=0.4,
        rescale=1./255,
        featurewise_center=True,
        fill_mode = 'reflect')

    img = load_img(img_path)
    x = img_to_array(img)
    x = x.reshape((1,) + x.shape)
    i = 0
    for batch in datagen.flow(x, batch_size = 1,
                            save_to_dir ='DataGeneration/train/Mist', save_prefix='Mist_X', save_format='jpeg'):
        i+= 1
        if i == 2001:
            break
    
    j = 0
    path, dirs, files = next(os.walk("DataGeneration/train/Mist"))
    file_count = len(files)
    if(file_count != 3000):
        for batch in datagen.flow(x, batch_size = 1,
                               save_to_dir ='DataGeneration/train/Mist', save_prefix='Mist_X_A', save_format='jpeg'):
            j+= 1
            if(j == 3000 - file_count):
                break
        
#Generate mist data with Y wrong.            
def GenerateDataMist_Y(img_path):
    datagen = ImageDataGenerator(
        height_shift_range=0.4,
        rescale=1./255,
        featurewise_center=True,
        fill_mode= 'constant', cval = 255)

    img = load_img(img_path)
    x = img_to_array(img)
    x = x.reshape((1,) + x.shape)
    i = 0
    for batch in datagen.flow(x, batch_size = 1,
                            save_to_dir ='DataGeneration/train/Mist', save_prefix='Mist_Y', save_format='jpeg'):
        i+= 1
        if i == 2001:
            break
        
    j = 0
    path, dirs, files = next(os.walk("DataGeneration/train/Mist"))
    file_count = len(files)
    if(file_count != 5000):
        for batch in datagen.flow(x, batch_size = 1,
                               save_to_dir ='DataGeneration/train/Mist', save_prefix='Mist_Y_A', save_format='jpeg'):
            j+= 1
            if(j == 5000 - file_count):
                break
                
#Generate true validation data to service fit model
def GenerateDataTest(img_path):
    datagen = ImageDataGenerator(
        featurewise_center=True,
        rescale=1./255,
        fill_mode = 'nearest')

    img = load_img(img_path)
    x = img_to_array(img)
    x = x.reshape((1,) + x.shape)

    i = 0
    for batch in datagen.flow(x, batch_size = 1,
                            save_to_dir ='DataGeneration/validation/Data', save_prefix='Data', save_format='jpeg'):
        i+= 1
        if i == 201:
            break
            
    j = 0
    path, dirs, files = next(os.walk("DataGeneration/validation/Data"))
    file_count = len(files)
    if(file_count != 200):
        for batch in datagen.flow(x, batch_size = 1,
                               save_to_dir ='DataGeneration/validation/Data', save_prefix='Data_A', save_format='jpeg'):
            j+= 1
            if(j == 200 - file_count):
                break

def GenerateDataTestMist(img_path):
    datagen = ImageDataGenerator(
        width_shift_range=0.3,
        rescale=1./255,
        featurewise_center=True,
        height_shift_range=0.3,
        fill_mode= 'constant', cval = 255)

    img = load_img(img_path)
    x = img_to_array(img)
    x = x.reshape((1,) + x.shape)
    
    i = 0
    for batch in datagen.flow(x, batch_size = 1,
                            save_to_dir ='DataGeneration/validation/Mist', save_prefix='Mist', save_format='jpeg'):
        i+= 1
        if i == 201:
            break
            
    j = 0
    path, dirs, files = next(os.walk("DataGeneration/validation/Mist"))
    file_count = len(files)
    if(file_count != 200):
        for batch in datagen.flow(x, batch_size = 1,
                               save_to_dir ='DataGeneration/validation/Mist', save_prefix='Mist_A', save_format='jpeg'):
            j+= 1
            if(j == 200 - file_count):
                break
                
#Generate validation mist X data to service fit model            
def GenerateDataTest_X(img_path):
    datagen = ImageDataGenerator(
        width_shift_range=0.4,
        rescale=1./255,
        featurewise_center=True,
        fill_mode = 'reflect')

    img = load_img(img_path)
    x = img_to_array(img)
    x = x.reshape((1,) + x.shape)
    i = 0
    for batch in datagen.flow(x, batch_size = 1,
                            save_to_dir ='DataGeneration/validation/Mist', save_prefix='Mist_X', save_format='jpeg'):
        i+= 1
        if i == 301:
            break
            
    j = 0
    path, dirs, files = next(os.walk("DataGeneration/validation/Mist"))
    file_count = len(files)
    if(file_count != 500):
        for batch in datagen.flow(x, batch_size = 1,
                               save_to_dir ='DataGeneration/validation/Mist', save_prefix='Mist_X_A', save_format='jpeg'):
            j+= 1
            if(j == 500 - file_count):
                break
            
#Generate validation mist Y data to service fit model             
def GenerateDataTest_Y(img_path):
    datagen = ImageDataGenerator(
        height_shift_range=0.4,
        rescale=1./255,
        featurewise_center=True,
        fill_mode= 'constant', cval = 255)

    img = load_img(img_path)
    x = img_to_array(img)
    x = x.reshape((1,) + x.shape)
    
    i = 0
    for batch in datagen.flow(x, batch_size = 1,
                            save_to_dir ='DataGeneration/validation/Mist', save_prefix='Mist_Y', save_format='jpeg'):
        i+= 1
        if i == 301:
            break
        
    j = 0
    path, dirs, files = next(os.walk("DataGeneration/validation/Mist"))
    file_count = len(files)
    if(file_count != 800):
        for batch in datagen.flow(x, batch_size = 1,
                               save_to_dir ='DataGeneration/validation/Mist', save_prefix='Mist_Y_A', save_format='jpeg'):
            j+= 1
            if(j == 800 - file_count):
                break
            
            
def ComplieModel():
    if K.image_data_format() == 'channels_first':
        input_shape = (3, template_width, template_height)
    else:
        input_shape = (template_width, template_height, 3)

    model = Sequential()
    model.add(Conv2D(32, (3, 3), input_shape=input_shape))
    model.add(Activation('relu'))
    model.add(MaxPooling2D(pool_size=(2, 2)))

    model.add(Conv2D(32, (3, 3)))
    model.add(Activation('relu'))
    model.add(MaxPooling2D(pool_size=(2, 2)))

    model.add(Conv2D(64, (3, 3)))
    model.add(Activation('relu'))
    model.add(MaxPooling2D(pool_size=(2, 2)))

    model.add(Flatten())
    model.add(Dense(64))
    model.add(Activation('relu'))
    model.add(Dropout(0.5))
    model.add(Dense(1))
    model.add(Activation('sigmoid'))

    model.compile(loss='binary_crossentropy',optimizer='rmsprop',metrics=['binary_accuracy'])
    
    return model

def TrainModel(train_data_dir, validation_data_dir, model, model_directory, template_width, template_height):
    #Default
	# giả sử models = model1;model2;model3
    nb_train_samples = 7000
    nb_validation_samples = 1000
    epochs = 30
    batch_size = 20
    #template = cv2.imread(img_path,0)
    #w,h = template.shape[::-1]
    train_datagen = ImageDataGenerator(rescale=1. / 255)
    test_datagen = ImageDataGenerator(rescale= 1./ 255)

    train_generator = train_datagen.flow_from_directory(
        train_data_dir,
        target_size=(template_width, template_height),
        batch_size = batch_size,
        class_mode = 'binary')

    validation_generator = test_datagen.flow_from_directory(
        validation_data_dir,
        target_size=(template_width, template_height),
        batch_size=batch_size,
        class_mode= 'binary')

    model.fit_generator(
        train_generator,
        steps_per_epoch=nb_train_samples // batch_size,
        epochs=epochs,
        validation_data=validation_generator,
        validation_steps=nb_validation_samples // batch_size)
    model.save(model_directory)
    
    return 1
    
# return location of pixels when predict finished    
class MultiThread(threading.Thread):
    def __init__(self, name, model, template_width, template_hight, main_Image, start_X, start_Y, end_X, end_Y, delay):
        threading.Thread.__init__(self)
        self._stop_event = threading.Event()
        self.name = name
        self.model = model
        self.template_width = template_width
        self.template_height = template_height
        self.main_Image = main_Image
        self.start_X = start_X
        self.start_Y = start_Y
        self.end_X = end_X
        self.end_Y = end_Y
        self.delay = delay
        self.session = K.get_session()
        self.graph = tf.get_default_graph()
        #self.graph.finalize() # finalize
    
    def run(self):
        #print("Starting " + self.name)
        try: 
            prediction(self.name, self.main_Image, self.model, self.start_X, self.start_Y, self.end_X, self.end_Y,
						self.session, self.graph, fileLocation, template_width, template_height)
        except:
            raise
    
    def stop(self):
        self._stop_event.set() 
        
    def stopped(self):
        return self._stop_event.is_set()

def prediction(name, main_image_path, model, start_X, start_Y, end_X, end_Y, 
                        session, graph, location_txt_path, template_width, template_height):
    im = cv2.imread(main_image_path)
    j = start_Y
    #template_width = 46
    #template_hight = 46
    i = start_X
    while i < end_X:
        x = im[j : j + template_height , i : i + template_width]
        if(x.shape != (template_width, template_height, 3)):
            break
        x = x.reshape((1,) + x.shape)
        with session.as_default():
            with graph.as_default():
                res = model.predict(x)
        if res == 0:
            #print(name)
            #print(j + template_height, i + template_width) # tọa độ (y,x)
            located = str(i) + ',' + str(j) + ',' + str(i + template_width) + ',' + str(j + template_height) +'\n'
            write_to_file(location_txt_path,located,0)
        i = i + 1
    
#def write_to_file(filename, content, condition):
#    global lck
#    lck.acquire()
#    with open(filename, 'a') as f:
#        f.write(content)
#        f.close()
#    lck.release()
    
def write_to_file(filename, content, condition):
    global lck
    lck.acquire()
    if(condition == 3 or condition == 2):
        with open(filename, 'r+') as f:
            f.seek(0)
            f.write(str(content))
            f.close()
    else:
        with open(filename, 'a') as f:
            f.write(content)
            f.close()
    lck.release()
# hàm xóa hết hình trong folder train + test
def delete_generate_file(path):
    for filename in os.listdir(path):
            filepath = os.path.join(path, filename)
            try:
                shutil.rmtree(filepath)
            except OSError:
                os.remove(filepath)

def detection(train_folder,validation_folder, model_directory, template_width, template_height):
    if(TrainModel(train_folder, validation_folder, ComplieModel(), model_directory, template_width, template_height) == 1):
        delete_generate_file('./DataGeneration/train/Data')
        delete_generate_file('./DataGeneration/train/Mist')
        delete_generate_file('./DataGeneration/validation/Data')
        delete_generate_file('./DataGeneration/validation/Mist')
        print('Training model is finished.')
        print('Prediction is processing ! Please wait a few minutes.')
        model = load_model(model_directory)
        #error = 0
        try:
            y = 0
            while y < (main_height - 5 - template_height):
                #model_path = _model_dir + '/' + name # Load tên của model trong folder chứa nó.
                thread1 = MultiThread("thread 1", model, template_width, template_height, main_Image,0,y,main_width,main_height,1)
                thread2 = MultiThread("thread 2", model, template_width, template_height, main_Image,0,y+1,main_width,main_height,5)
                thread3 = MultiThread("thread 3", model, template_width, template_height, main_Image,0,y+2,main_width,main_height,10)
                thread4 = MultiThread("thread 4", model, template_width, template_height, main_Image,0,y+3,main_width,main_height,15)
                thread5 = MultiThread("thread 5", model, template_width, template_height, main_Image,0,y+4,main_width,main_height,8)
                
                thread1.start()
                thread2.start()
                thread3.start()
                thread4.start()
                thread5.start()
                
                thread1.join()
                thread2.join()
                thread3.join()
                thread4.join()
                thread5.join()


                thread1.stop()
                thread2.stop()
                thread3.stop()
                thread4.stop()
                thread5.stop()

                y = y + 5
        
                    
        except:
            print ("Error")
            write_to_file(fileLocation,2,2)
            #error = 1
        K.clear_session()        
    #if error == 0:
        #write_to_file(fileLocation,3,3)
    #else:
        #write_to_file(fileLocation,2,2)
        
				
if __name__ == '__main__':
    #print(img_path)
    #array = os.listdir(img_path)
    i = 0
    for filename in os.listdir(img_path):
        im_path = img_path +'/'+ filename
        name = model_dir + str(i) + '.h5' 
        img = cv2.imread(os.path.join('D:/Dept/test',filename),0) #get height and width of template image.
        template_width, template_height = img.shape[::-1]
        GenerateDataTrain(im_path)
        GenerateDataTrainMist(im_path)
        GenerateDataMist_X(im_path)
        GenerateDataMist_Y(im_path)
        #Validation
        GenerateDataTest(im_path)
        GenerateDataTestMist(im_path)
        GenerateDataTest_X(im_path)
        GenerateDataTest_Y(im_path)
        print('Generation data is finished.')
        detection('./DataGeneration/train','./DataGeneration/validation', name, template_width, template_height)
        i = i + 1
    write_to_file(fileLocation,3,3)
    print('Done')

    
    
    
    
